#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : QtPy
Version  : 1.3.1
Release  : 3
URL      : https://pypi.python.org/packages/b9/16/b801f43a911e644c3308f86f8c294a5a2d1e7c6d77a87122bdb03b29888d/QtPy-1.3.1.tar.gz
Source0  : https://pypi.python.org/packages/b9/16/b801f43a911e644c3308f86f8c294a5a2d1e7c6d77a87122bdb03b29888d/QtPy-1.3.1.tar.gz
Summary  : Provides an abstraction layer on top of the various Qt bindings (PyQt5, PyQt4 and PySide) and additional custom QWidgets.
Group    : Development/Tools
License  : MIT
Requires: QtPy-python3
Requires: QtPy-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
# QtPy: Abstraction layer for PyQt5/PyQt4/PySide2/PySide
## Project details
[![license](https://img.shields.io/pypi/l/qtpy.svg)](./LICENSE)
[![pypi version](https://img.shields.io/pypi/v/qtpy.svg)](https://pypi.python.org/pypi/qtpy)
[![Join the chat at https://gitter.im/spyder-ide/public](https://badges.gitter.im/spyder-ide/spyder.svg)](https://gitter.im/spyder-ide/public)

%package python
Summary: python components for the QtPy package.
Group: Default
Requires: QtPy-python3
Provides: qtpy-python

%description python
python components for the QtPy package.


%package python3
Summary: python3 components for the QtPy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the QtPy package.


%prep
%setup -q -n QtPy-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1515336163
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
