#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : QtPy
Version  : 1.7.1
Release  : 16
URL      : https://files.pythonhosted.org/packages/65/aa/8414c56373f1e00177e6dcfd139f799c0f11d7f23ee2d37ce9a0f606857f/QtPy-1.7.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/65/aa/8414c56373f1e00177e6dcfd139f799c0f11d7f23ee2d37ce9a0f606857f/QtPy-1.7.1.tar.gz
Summary  : Provides an abstraction layer on top of the various Qt bindings (PyQt5, PyQt4 and PySide) and additional custom QWidgets.
Group    : Development/Tools
License  : MIT
Requires: QtPy-license = %{version}-%{release}
Requires: QtPy-python = %{version}-%{release}
Requires: QtPy-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# QtPy: Abstraction layer for PyQt5/PyQt4/PySide2/PySide
[![license](https://img.shields.io/pypi/l/qtpy.svg)](./LICENSE)
[![pypi version](https://img.shields.io/pypi/v/qtpy.svg)](https://pypi.org/project/QtPy/)
[![conda version](https://img.shields.io/conda/vn/conda-forge/qtpy.svg)](https://www.anaconda.com/download/)
[![download count](https://img.shields.io/conda/dn/conda-forge/qtpy.svg)](https://www.anaconda.com/download/)
[![OpenCollective Backers](https://opencollective.com/spyder/backers/badge.svg?color=blue)](#backers)
[![Join the chat at https://gitter.im/spyder-ide/public](https://badges.gitter.im/spyder-ide/spyder.svg)](https://gitter.im/spyder-ide/public)<br>
[![PyPI status](https://img.shields.io/pypi/status/qtpy.svg)](https://github.com/spyder-ide/qtpy)
[![Build status](https://ci.appveyor.com/api/projects/status/62y6i02vhn4hefg0/branch/master?svg=true)](https://ci.appveyor.com/project/spyder-ide/qtpy/branch/master)
[![CircleCI](https://circleci.com/gh/spyder-ide/qtpy.svg?style=shield)](https://circleci.com/gh/spyder-ide/qtpy)
[![Coverage Status](https://coveralls.io/repos/github/spyder-ide/qtpy/badge.svg?branch=master)](https://coveralls.io/github/spyder-ide/qtpy?branch=master)

%package license
Summary: license components for the QtPy package.
Group: Default

%description license
license components for the QtPy package.


%package python
Summary: python components for the QtPy package.
Group: Default
Requires: QtPy-python3 = %{version}-%{release}
Provides: qtpy-python

%description python
python components for the QtPy package.


%package python3
Summary: python3 components for the QtPy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the QtPy package.


%prep
%setup -q -n QtPy-1.7.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1557166519
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/QtPy
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/QtPy/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/QtPy/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
